version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: vitahub-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - vitahub_monitoring

  grafana:
    image: grafana/grafana:10.1.0
    container_name: vitahub-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: vitahub_grafana
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - '3001:3000'
    networks:
      - vitahub_monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  vitahub_monitoring:
    driver: bridge
