global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['api:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'vitahub-api'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:9104']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'vitahub-mysql'

  - job_name: 'node'
    static_configs:
      - targets: ['api:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'vitahub-node'
